/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.testworkspace2.pet.api_name_pet;

import com.testworkspace2.pet.api_name_pet.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "0.5.0";
	public String genVersion = "2.152.1";
	public String userAgent = "speakeasy-sdk/java 0.5.0 2.152.1 1.0.0 <no value>";
	
	
}