/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.testworkspace2.pet.api_name_pet.models.operations;

import com.testworkspace2.pet.api_name_pet.utils.SpeakeasyMetadata;


public class ListPetsRequest {
    /**
     * How many items to return at one time (max 100)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Integer limit;

    public ListPetsRequest withLimit(Integer limit) {
        this.limit = limit;
        return this;
    }
    
    public ListPetsRequest(){}
}
