/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.testworkspace2.pet.api_name_pet.utils;

import java.lang.reflect.Field;

public class HeaderMetadata extends Metadata {
    public String style = "simple";
    public boolean explode;
    public String name;

    // headerParam:style=simple,explode=false,name=apiID
    public static HeaderMetadata parse(Field field) throws IllegalArgumentException, IllegalAccessException {
        HeaderMetadata result = new HeaderMetadata();
        result = (HeaderMetadata) parse("header", result, field);
        return result;
    }

    private HeaderMetadata() {
    }
}
